ДЗ 1
ABoltachev/cpp_homeworks pull request #5
Opened 2022-11-27 16:45 UTC by nikzagl

2022-12-03 12:51 UTC, ABoltachev requested changes

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +class AddressBook;
Если вы делаете целый класс дружественным, то объявлять его заранее необязательно

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +        Node() = default;
Данный конструктор не будет работать без конструктора по умолчанию у Employee

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    Employee& operator [](uint32_t id);
Необходима константная версия этого оператора

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    Employee& operator [](std::string name);
Необходима константная версия этого оператора

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    void print_employees();
Не вижу перегрузки оператора << для вывода на экран

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    friend std::ostream& operator<<(std::ostream&, Employee&);
Здесь должна быть константная ссылка на Employee

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    bool operator ==(Employee& other);
Данный метод должен быть константным как и его аргуент

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    bool operator !=(Employee & other);
Данный метод должен быть константным как и его аргуент

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    Employee(uint32_t id, std::string name, uint16_t grade){m_id = id;m_name = name;m_grade = grade;}
Передача сложного типа по значению
Вместо std::string должно быть const std::string&

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    void add_employee(uint32_t id, std::string name, uint16_t grade);
Передача сложного типа по значению
Вместо std::string должно быть const std::string&

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    Node* at(std::string name);
Передача сложного типа по значению
Вместо std::string должно быть const std::string&

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    Node* at ( uint32_t id);
Необходима константная версия этого метода

2022-12-03 12:51 UTC, ABoltachev commented on address_book.h
> +    Node* at(std::string name);
Необходима константная версия этого метода

2022-12-03 12:51 UTC, ABoltachev commented on address_book.cpp
> +        delete (cur_node);
Это оператор а не функция. delete cur_node

2022-12-03 12:51 UTC, ABoltachev commented on address_book.cpp
> +            delete(temp);
Это оператор а не функция. delete temp

2022-12-03 20:54 UTC, ABoltachev requested changes

2022-12-03 20:54 UTC, ABoltachev commented on address_book.h
> +    const Employee& operator [](std::string& name) const;
Должно быть две версии
const Employee& operator [](const std::string& name) const
и
Employee& operator [](const std::string& name)

2022-12-03 20:54 UTC, ABoltachev commented on address_book.h
> +    const Node* at (const uint32_t id) const;
Когда делаете метод константным это не значит, что и аргументы должны быть константными
Если аргумент передается по значению (базовые типы) делать его константным необязательно
Если аргумент передается по ссылке (сложные типы) то в случае если его значение предполагается менять в методе(функции) она не должна быть константной, а иначе константная

2022-12-04 08:00 UTC, nikzagl commented on address_book.h
> +    const Employee& operator [](std::string& name) const;
а чем они между собой будут отличаться?

2023-02-07 21:00 UTC, merged