HW(1): mmklochickhin
ABoltachev/cpp_homeworks pull request #8
Opened 2022-11-28 18:04 UTC by EverlastingSuffering

2022-12-03 13:10 UTC, ABoltachev requested changes

2022-12-03 13:10 UTC, ABoltachev commented on AddressBookOperators/adr_book.hpp
> +    struct Employee
Правильнее использовать класс, а не структуру, так как хранит не только данные
Данные должны быть скрыты
AddressBook должен быть дружественным для Employee

2022-12-03 13:10 UTC, ABoltachev commented on AddressBookOperators/adr_book.hpp
> +        friend bool operator==(const Employee& a, const Employee& b);
Нет необходимости делать их дружественными

2022-12-03 13:10 UTC, ABoltachev commented on AddressBookOperators/adr_book.hpp
> +        friend bool operator!=(const Employee& a, const Employee& b);
Нет необходимости делать их дружественными

2022-12-03 13:10 UTC, ABoltachev commented on AddressBookOperators/adr_book.hpp
> +    Employee& operator[](std::string name);
Должны также существовать константные версии

2022-12-03 13:10 UTC, ABoltachev commented on AddressBookOperators/adr_book.hpp
> +    Employee& operator[](uint32_t id);
Должны также существовать константные версии

2022-12-03 13:10 UTC, ABoltachev commented on AddressBookOperators/adr_book.hpp
> +#include <stdint.h>
Не вижу header guards

2022-12-04 05:11 UTC, EverlastingSuffering commented on AddressBookOperators/adr_book.hpp
> +    struct Employee
Структура ничем не отличается от класса, кроме как тем, что по дефолту там поля public. Так было удобнее

2022-12-04 05:12 UTC, EverlastingSuffering commented on AddressBookOperators/adr_book.hpp
> +        friend bool operator==(const Employee& a, const Employee& b);
Это просто такой способ перегрузки. Я так захотел перегрузить. Не вижу проблемы.

2022-12-04 05:14 UTC, EverlastingSuffering commented on AddressBookOperators/adr_book.hpp
> +    Employee& operator[](std::string name);
Как можно перегрузить operator[] дважды с одними и теми же аргументами? Или вы про методы? Тогда добавить методы с другими названиями, но тем же функционалом?

2022-12-04 05:16 UTC, EverlastingSuffering commented on AddressBookOperators/adr_book.hpp
> +    Employee& operator[](std::string name);
Что они тогда возвращать будут, если мы не найдем нужного Employee?

2022-12-04 08:59 UTC, EverlastingSuffering commented on AddressBookOperators/adr_book.hpp
> +    struct Employee
Данные я хотел скрыть, но в тогда из функции перегрузки IO операторов не будут видны поля Employee. К тому же не вижу большого смысла скрывать данные. Почему бы не позволить пользователю менять их напрямую? А геттеры я просто забыл убрать после экспериментов.
AddressBook итак дружественный там. Но в ТЗ не написано, что поля должны быть private, поэтому сделал как удобнее.

2022-12-04 09:32 UTC, EverlastingSuffering commented on AddressBookOperators/adr_book.hpp
> +    Employee& operator[](std::string name);
Или вы имеете в виду const operator[], который будет вызываться для const объектов? Тогда что он будет делать, если такого элемента нет?

2022-12-04 09:39 UTC, EverlastingSuffering commented on AddressBookOperators/adr_book.hpp
> +    Employee& operator[](std::string name);
Не понимаю, в чем смысл тогда константного объекта AddressBook, если при этом нельзя будет ее редактировать никак, в том числе и заполнить ее с консоли.

2023-02-07 21:07 UTC, merged