Hw1 gagolubev
ABoltachev/cpp_homeworks pull request #9
Opened 2022-11-29 15:14 UTC by GerogeGol

2022-12-03 13:15 UTC, ABoltachev requested changes

2022-12-03 13:15 UTC, ABoltachev commented on AddressBookOperators/address_book.hpp
> +   public:
данные должны быть скрыты
Доступ к ним в AddressBook через дружественным классом

2022-12-03 13:15 UTC, ABoltachev commented on AddressBookOperators/address_book.hpp
> +    bool operator==(const Employee& emp);
Должны быть константными методами

2022-12-03 13:15 UTC, ABoltachev commented on AddressBookOperators/address_book.hpp
> +    bool operator!=(const Employee& emp);
Должны быть константными методами

2022-12-03 13:15 UTC, ABoltachev commented on AddressBookOperators/address_book.hpp
> +    Employee& operator[](const size_t id);
Нужны дополнительно константные версии операторов

2022-12-03 13:15 UTC, ABoltachev commented on AddressBookOperators/address_book.hpp
> +    Employee& operator[](const std::string& name);
Нужны дополнительно константные версии операторов

2022-12-03 13:15 UTC, ABoltachev commented on AddressBookOperators/address_book.hpp
> +    friend class Employee;
Должен быть дружественным не Employee к AddressBook, а наоборот

2022-12-03 15:58 UTC, GerogeGol commented on AddressBookOperators/address_book.hpp
> +    friend class Employee;
Поменял

2022-12-03 15:59 UTC, GerogeGol commented on AddressBookOperators/address_book.hpp
> +    Employee& operator[](const std::string& name);
Сделал

2022-12-03 15:59 UTC, GerogeGol commented on AddressBookOperators/address_book.hpp
> +    Employee& operator[](const size_t id);
Сделал

2022-12-03 15:59 UTC, GerogeGol commented on AddressBookOperators/address_book.hpp
> +    bool operator!=(const Employee& emp);
Поменял

2022-12-03 15:59 UTC, GerogeGol commented on AddressBookOperators/address_book.hpp
> +    bool operator==(const Employee& emp);
Сделал

2022-12-03 16:00 UTC, GerogeGol commented on AddressBookOperators/address_book.hpp
> +   public:
Добавил

2022-12-03 21:05 UTC, ABoltachev requested changes

2022-12-03 21:05 UTC, ABoltachev commented on AddressBookOperators/address_book.cpp
>  {
Зачем убрали защиту от самокопирования?

2022-12-03 21:05 UTC, ABoltachev commented on AddressBookOperators/address_book.hpp
> +    const Employee& operator[](const size_t id) const;
Когда делаете метод константным это не значит, что и аргументы должны быть константными
Если аргумент передается по значению (базовые типы) делать его константным необязательно
Если аргумент передается по ссылке (сложные типы) то в случае если его значение предполагается менять в методе(функции) она не должна быть константной, а иначе константная

2022-12-03 21:05 UTC, ABoltachev commented on AddressBookOperators/address_book.cpp
> +    return find(name);
Зациклится в рекурсии
Из константного метода можно вызвать только константный метод

2022-12-03 21:05 UTC, ABoltachev commented on AddressBookOperators/address_book.cpp
> +    return find(id);
Зациклится в рекурсии
Из константного метода можно вызвать только константный метод

2022-12-04 07:43 UTC, GerogeGol commented on AddressBookOperators/address_book.cpp
>  {
Ой, я что то даже не заметил как это удалил(

2022-12-04 07:48 UTC, GerogeGol commented on AddressBookOperators/address_book.cpp
> +    return find(name);
А как можно исправить код, чтобы обойтись без самокопирования?

2022-12-04 07:49 UTC, GerogeGol commented on AddressBookOperators/address_book.cpp
> +    return find(id);
Такой же вопрос как для 185 строки

2022-12-04 07:51 UTC, GerogeGol commented on AddressBookOperators/address_book.hpp
> +    const Employee& operator[](const size_t id) const;
Ну я сделал агрумент id константым просто для логичности. В методе он не изменяется и поэтому он const

2023-02-07 21:10 UTC, merged